SELECT * WHERE {
    ?reply a review:Review;
        review:issuedBy ?comment_responsible;
        review:aboutRevision ?revision;
        review:hasComment ?comment.
        ?comment a review:Comment;
        rdfs:label ?comment_text;
        review:issuedBy ?author;
        prov:generatedAtTime ?date;
        review:aboutObject ?row .
        ?row mel:tagNumber ?tagNumber .
       
        ?revision rev:describes ?document.
}