name: 🚀 Build and Publish DtoTransformer 🚀

on:
  release:
    types: [published] 

jobs:
  publish:
    name: "Nuget publish"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore ./src/DtoTransformer/DtoTransformer

      - name: Build solution
        run: dotnet build ./src/DtoTransformer/DtoTransformer --no-restore --configuration Release 

      - name: Create artifact
        run: dotnet pack ./src/DtoTransformer/DtoTransformer --no-restore --no-build --configuration Release --output ${{ github.workspace }}/out /p:'description="A library for using revisions.";PackageVersion="${{ github.event.release.name }}'

      - name: Publish
        run: dotnet nuget push ${{ github.workspace }}/out/Review*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
